import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import "./affirmme-theme.css";
import { ThemeProvider } from "../components/theme/ThemeProvider";
import { ProfileProvider } from "../components/profile/ProfileProvider";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    images: [
      {
        url: 'https://bolt.new/static/og_default.png',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    images: [
      {
        url: 'https://bolt.new/static/og_default.png',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="comic">
     <body className={inter.className}>
     <ThemeProvider>
  <ProfileProvider>
    {children}
  </ProfileProvider>
</ThemeProvider>
</body>
    </html>
  );
}
